In [1]:
import os
import sys
path_to_this_notebook = os.path.abspath('.')
PATH_TO_PROJECT = path_to_this_notebook[: path_to_this_notebook.find('notebooks')]
sys.path.append(PATH_TO_PROJECT)

import numpy as np
import re
import pandas as pd

In [3]:
path_to_recordings_metadata = PATH_TO_PROJECT + 'data/'
metadata = pd.read_csv(path_to_recordings_metadata + 'recordings_metadata.csv')

In [54]:
new_cols = ['split', 'labeled', 'traced', 'splits checked',  'labels checked', 'traces checked']

In [22]:
rec_name

'03092019 Mic 2 Com 6 Vid Left Part 3.npy'

In [75]:
new_cols_vals = []

for rec_name, rec_path, stage in metadata[['name', 'path', 'processing stage']].values:
    try:
        rec_split = 'auto'
        rec_labeled = False
        rec_traced = False
        
        splits_checked = False
        labels_checked = False
        traces_checked = False
        
        txt = pd.read_csv(rec_path + rec_name.replace('npy', 'txt'), sep='\t')
        sound_values = txt['cl'].unique()
        if len(sound_values) == 0:
            new_cols_vals.append((rec_split, rec_labeled, rec_traced,
                                  splits_checked, labels_checked, traces_checked))
            continue
        
        elif not ('sound' in sound_values and 
                  ((len(sound_values) == 1) or (len(sound_values) == 2 and 'noise' in sound_values))):
            rec_labeled = 'auto'
            
        if stage == 'split and checked':
            splits_checked = True
        elif stage == 'labeled and checked':
            splits_checked = True
            labels_checked = True
            
        traces_in_rec = [t[:t.find('_')] for t in os.listdir(rec_path.replace('recordings', 'traces')) 
                         if (rec_name[:-3] in t) and 'trace' in t]
        if len(traces_in_rec) > 0:
            rec_traced = 'auto'
            if 'freshtrace' not in traces_in_rec:
                traces_checked = True
                
                
        
    except:
        rec_split = False
        rec_labeled = False
        rec_traced = False
        splits_checked = False
        labels_checked = False
        traces_checked = False
    if rec_labeled == False and labels_checked:
        print(123)
        break
    new_cols_vals.append((rec_split, rec_labeled, rec_traced, 
                          splits_checked, labels_checked, traces_checked))
new_cols_vals = np.array(new_cols_vals)

In [83]:
ind = np.random.randint(0, 1670)
metadata[ind : ind +10]

,colony,date,experiment,name,number,path,processing stage,ratids,split,splits checked,labeled,labels checked,traced,traces checked
827,targaryen,21-11-18,classification,targaryen_21-11-18_4043_0000048.npy,48.0,/home/gr1/Projects/Naked-mole-rat-voices/data/...,labeled and checked,4043,auto,True,auto,True,False,False
828,stark,23-12-17,classification,stark_23-12-17_8318_0000002.npy,2.0,/home/gr1/Projects/Naked-mole-rat-voices/data/...,labeled and checked,8318,auto,True,auto,True,False,False
829,baratheon,09-02-18,classification,baratheon_09-02-18_9440_0000047.npy,47.0,/home/gr1/Projects/Naked-mole-rat-voices/data/...,traced and checked,9440,auto,False,auto,False,auto,False
830,targaryen,24-04-18,classification,targaryen_24-04-18_0545_3984_0000036.npy,36.0,/home/gr1/Projects/Naked-mole-rat-voices/data/...,labeled and checked,0545_3984,auto,True,auto,True,False,False
831,baratheon,09-02-18,classification,baratheon_09-02-18_0855_9449_0000029.npy,29.0,/home/gr1/Projects/Naked-mole-rat-voices/data/...,traced and checked,0855_9449,auto,False,auto,False,auto,False
832,targaryen,31-03-18,classification,targaryen_31-03-18_3981_0000022.npy,22.0,/home/gr1/Projects/Naked-mole-rat-voices/data/...,labeled and checked,3981,auto,True,auto,True,False,False
833,targaryen,21-11-18,classification,targaryen_21-11-18_1536_1411_0000036.npy,36.0,/home/gr1/Projects/Naked-mole-rat-voices/data/...,labeled and checked,1536_1411,auto,True,auto,True,False,False
834,baratheon,24-08-17,classification,baratheon_24-08-17_2131_2097_0000007.npy,7.0,/home/gr1/Projects/Naked-mole-rat-voices/data/...,traced and checked,2131_2097,auto,False,auto,False,auto,False
835,stark,07-03-19,classification,stark_07-03-19_9597_8314_0000001.npy,1.0,/home/gr1/Projects/Naked-mole-rat-voices/data/...,labeled and checked,9597_8314,auto,True,auto,True,False,False
836,targaryen,21-11-18,classification,targaryen_21-11-18_1538_4057_0000068.npy,68.0,/home/gr1/Projects/Naked-mole-rat-voices/data/...,labeled and checked,1538_4057,auto,True,auto,True,False,False

In [77]:
for col_name, col_val in zip(new_cols, new_cols_vals.T):
    metadata[col_name] = col_val